### ISSUE TITLE
npm install 之后 npm run dev 报Cannot find module 'vs/editor/contrib/gotoSymbol/goToCommands'

### ISSUE THREAD

**Issue by hackeryutu** [Nepxion/DiscoveryUI#6]
node版本 v10.21.0

npm install
npm run dev
 报Cannot find module 'vs/editor/contrib/gotoSymbol/goToCommands'

异常信息如下
Error: Cannot find module 'vs/editor/contrib/gotoSymbol/goToCommands'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at resolveMonacoPath (/Users/charles/Documents/project/nepxion/DiscoveryUI/node_modules/monaco-editor-webpack-plugin/out/index.js:34:28)
    at use.options.pre.featurePaths.map (/Users/charles/Documents/project/nepxion/DiscoveryUI/node_modules/monaco-editor-webpack-plugin/out/index.js:173:63)
    at Array.map (<anonymous>)
    at createLoaderRules (/Users/charles/Documents/project/nepxion/DiscoveryUI/node_modules/monaco-editor-webpack-plugin/out/index.js:173:43)
    at MonacoEditorWebpackPlugin.apply (/Users/charles/Documents/project/nepxion/DiscoveryUI/node_modules/monaco-editor-webpack-plugin/out/index.js:91:23)
    at Compiler.apply (/Users/charles/Documents/project/nepxion/DiscoveryUI/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/charles/Documents/project/nepxion/DiscoveryUI/node_modules/webpack/lib/webpack.js:33:19)
    at startDevServer (/Users/charles/Documents/project/nepxion/DiscoveryUI/node_modules/webpack-dev-server/bin/webpack-dev-server.js:367:16)
    at processOptions (/Users/charles/Documents/project/nepxion/DiscoveryUI/node_modules/webpack-dev-server/bin/webpack-dev-server.js:350:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by HaojunRen** [comment]
请用Nacos、Apollo或者Redis做灰度蓝绿规则发布
